### ISSUE TITLE
[Feature] new way to record Question.

### ISSUE THREAD

**Issue by AlexShyXie** [hedyhli/aosr#1]
Your plugin was really wonderful, which effectively solve the issue of multiple blank cloze questions in the original plugin. However, there is a problem in the use of automatic encoding to read the question, as it may make the content of notes unreadable. Is there any other way to resolve this issue?

**Comment by hedyhli** [comment]
Hi, I'm not sure what you mean by automatic encoding. Could you show me examples or screenshots of cases where the note is unreadable?

**Comment by AlexShyXie** [comment]
> Hi, I'm not sure what you mean by automatic encoding. Could you show me examples or screenshots of cases where the note is unreadable?

I like Tag Folder and Tag wrangler to organize my tag, but the link of blocks would broken the interface.
![image](https://github.com/hedyhli/aosr/assets/49368033/0e4cb262-c423-4837-b3dc-9c967b5eb85f)

What's more, the json data inseted in the last of file also made the note too long:
![image](https://github.com/hedyhli/aosr/assets/49368033/92d4c37d-771f-406e-b7be-70d2782887c7)

**Comment by AlexShyXie** [comment]
I'm sorry, do I make a mistake to raise issue in the wrong git repo?

**Comment by hedyhli** [comment]
No worries!

I see you've opened the issue there so I'll close this one now.

(Note to other readers: issues related to the features I've introduced in this fork specifically can still be opened in this repo)
